# Generated by Django 2.2 on 2019-04-10 08:17

import data_store.forms
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=data_store.forms.DjangoQuerysetJSONEncoder)),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=data_store.forms.DjangoQuerysetJSONEncoder)),
                ('is_success', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
