# Generated by Django 2.1.2 on 2018-10-14 18:46

import data_store.forms
from django.conf import settings
from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('landing_url', models.URLField(default=None, max_length=2048)),
                ('expiry_age', models.IntegerField(editable=False, null=True)),
                ('expiry_time', models.DateTimeField(editable=False, null=True)),
                ('time_on_site', models.IntegerField(editable=False, null=True)),
                ('user_agent', models.TextField(editable=False, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=data_store.forms.DjangoQuerysetJSONEncoder)),
                ('user', models.ForeignKey(db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='WebEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=data_store.forms.DjangoQuerysetJSONEncoder)),
                ('marketing_params', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('referrer', models.URLField(max_length=2048)),
                ('url', models.URLField(max_length=2048)),
                ('url_kwargs', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('url_name', models.CharField(max_length=100)),
                ('response_data', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('status_code', models.IntegerField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=6)),
                ('browser', models.CharField(max_length=30)),
                ('browser_version', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=30)),
                ('device_model', models.CharField(max_length=30)),
                ('device_type', models.CharField(choices=[('PC', 'PC'), ('MOBILE', 'MOBILE'), ('TABLET', 'TABLET'), ('BOT', 'BOT'), ('UNKNOWN', 'UNKNOWN')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('ip_country', django_countries.fields.CountryField(max_length=2)),
                ('ip_region', models.CharField(max_length=255)),
                ('ip_city', models.CharField(max_length=255)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.Visitor')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
