# Generated by Django 2.1.1 on 2018-09-12 20:48

from django.db import migrations, models
import common.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('generated_otp', models.CharField(max_length=6)),
                ('otp_verified', models.NullBooleanField(default=None)),
            ],
            options={
                'abstract': False,
            },
            bases=(common.models.AbstractModelMixin, models.Model),
        ),
    ]
