# Generated by Django 2.1.1 on 2018-09-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_auto_20180912_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
