# Generated by Django 2.1.1 on 2018-09-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('otp', '0003_auto_20180915_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='author_id',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='author_type',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='otp_otpmodel_authored', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
