# Generated by Django 2.1.1 on 2018-09-17 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('otp', '0004_auto_20180917_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('author_id', models.CharField(max_length=128)),
                ('otp', models.CharField(max_length=6)),
                ('author_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='otp_otpattempt_authored', to='contenttypes.ContentType')),
            ],
        ),
    ]
