# Generated by Django 2.1.5 on 2019-03-15 08:20

from django.utils import timezone
from django.db import migrations, models
import logging
import pytz

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_otpattempt'),
        ('analytics', '0001_initial'), # Analytics migrations should have been applied in 'analytics' database
    ]

    operations = [
        migrations.AddField(
            model_name='otpattempt',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.datetime(year=1970, month=1, day=1, tzinfo=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otpattempt',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.datetime(year=1970, month=1, day=1, tzinfo=pytz.UTC)),
            preserve_default=False,
        ),
    ]
