# Generated by Django 2.1.5 on 2019-03-15 10:48

import account.otp.models
import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('otp', '0006_auto_20190315_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel_pii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('generated_otp', models.CharField(default=account.otp.models.generate_otp, max_length=6)),
                ('otp_verified', models.NullBooleanField(default=None)),
                ('author_id', models.CharField(max_length=128)),
                ('author_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='otp_otpmodel_pii_authored', to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'otp_otpmodel',
            },
            bases=(common.models.AbstractModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OTPAttempt_pii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('author_id', models.CharField(max_length=128)),
                ('otp', models.CharField(max_length=6)),
                ('author_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='otp_otpattempt_pii_authored', to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'otp_otpattempt',
            },
            bases=(common.models.AbstractModelMixin, models.Model),
        ),
        migrations.AlterModelTable(
            name='otpattempt',
            table='otp_otpattempt__deprecated',
        ),
        migrations.AlterModelTable(
            name='otpmodel',
            table='otp_otpmodel__deprecated',
        ),
    ]
